name: Selenium Test
 
on:
  push:
 
  pull_request:
    branches:
      - main
  workflow_dispatch:

 
jobs:
  selenium_tests_job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
 
    - uses: browser-actions/setup-chrome@latest
 
    - name: Run Selenium tests
      run:   mvn clean test 
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: upload-results
          path: target/surefire-reports
